export const mySkills = [
  { title: 'Flutter', icon: 'flutter' },
  { title: 'Firebase', icon: 'firebase' },
  { title: 'C', icon: 'c' },
  { title: 'C++', icon: 'cpp' },
  { title: 'Python', icon: 'python' },
  { title: 'Dart', icon: 'dart' },
  { title: 'SQL', icon: 'sql' },
  { title: 'HTML', icon: 'html' },
  { title: 'CSS', icon: 'css' },
  { title: 'JavaScript', icon: 'javascript' },
  { title: 'TypeScript', icon: 'typescript' },
  { title: 'ReactJS', icon: 'react' },
  { title: 'NextJS', icon: 'nextjs' },
  { title: 'NodeJS', icon: 'nodejs' },
  { title: 'ExpressJS', icon: 'express' },
  { title: 'MongoDB', icon: 'mongodb' },
  { title: 'Git', icon: 'git' },
  { title: 'Tableau', icon: 'tableau' },
  { title: 'Microsoft Power BI', icon: 'powerbi' },
  { title: 'Data Analysis', icon: 'data-analysis' },
  { title: 'Machine Learning', icon: 'machine-learning' },
  { title: 'Image Preprocessing', icon: 'image-preprocessing' },
];
